### ISSUE TITLE
Update for 1.20 doesn't work on 1.20

### ISSUE THREAD

**Issue by Tapacywka** [chloecdn/optionfocusfix#3]
https://mclo.gs/h5CUH3A

**Comment by LunaticWasTaken** [comment]
That's weird, when i tested it inside my IDE it worked fine. i'm going to look at it.

**Comment by LunaticWasTaken** [comment]
I uploaded the 1.2.1 to Modrinth. It was crashing due to a bug with loom, so i updated to 1.2, which fixes the issue.
Some more info is provided in the changelog, if someone reads this and wants to know more.

If it still happens (doesn't for me on PrismLauncher), i'm keeping this Issue open for now, just in case.

**Comment by Tapacywka** [comment]
Thanks a lot for such a quick response! I started it up and everything is working great now)

**Comment by LunaticWasTaken** [comment]
Sure, no problem.

If it works, then i'll close the issue, but i'll keep it pinned just in case.
